### ISSUE TITLE
TypeError: Object of type 'function' is not JSON serializable (simpleui/templatetags/simpletags.py custom_button)

### ISSUE THREAD

**Issue by excelwang** [newpanjing/simpleui#112]
**bug描述**
Internal Server Error: /clouds/instanceoperation/
Traceback (most recent call last):
  File "/root/rabbit/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/rabbit/lib64/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/rabbit/lib64/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/defaulttags.py", line 37, in render
    output = self.nodelist.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/rabbit/lib64/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  **File "/root/rabbit/lib64/python3.6/site-packages/simpleui/templatetags/simpletags.py", line 363, in custom_button
    return json.dumps(data, cls=LazyEncoder)**
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/rabbit/lib64/python3.6/site-packages/simpleui/templatetags/simpletags.py", line 43, in default
    return super(LazyEncoder, self).default(obj)
  File "/root/rabbit/lib64/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'function' is not JSON serializable
[08/Jul/2019 21:00:50] "GET /clouds/instanceoperation/ HTTP/1.1" 500 523623

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：2.2.2
4.simpleui版本：latest

**Comment by newpanjing** [comment]
自定义action代码贴出来看看。

**Comment by newpanjing** [comment]
simpleui的版本号也发出来

**Comment by excelwang** [comment]
> simpleui的版本号也发出来

2.1.5

**Comment by excelwang** [comment]
> 自定义action代码贴出来看看。

@transaction.atomic
    def rerun(modeladmin, request, queryset):
        for op in queryset.select_for_update():
            op.status=OPERATION_STATUS.running.value
            op.started_time=now()
            op.completed_time=None
            if hasattr(op,'log'):
                op.log=''
            op.save()
            op.execute()
    rerun.short_description = "Re-run selected operations"
    actions=[rerun]
