### ISSUE TITLE
django 3.0 list页面报错

### ISSUE THREAD

**Issue by cn-jack** [newpanjing/simpleui#202]
**bug描述**

Error: Request failed with status code 500

错误日志：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 68, in __call__
    return self.application(environ, start_response)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/views/debug.py", line 264, in get_traceback_data
    frames = self.get_traceback_frames()
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/views/debug.py", line 424, in get_traceback_frames
    pre_context_lineno, pre_context, context_line, post_context = self._get_lines_from_file(
  File "/Users/cnjack/WorkSpace/git/venv/lib/python3.8/site-packages/django/views/debug.py", line 383, in _get_lines_from_file
    context_line = source[lineno]
IndexError: list index out of range
[17/Dec/2019 13:29:54] "POST /admin/user/user/ HTTP/1.1" 500 59

**重现步骤**
1.登录admin后台
2.点击左侧菜单，查看list列表信息
3.

**环境**

1.操作系统：
2.python版本：3.8
3.django版本：django 3.0
4.simpleui版本：1.0.7

**其他描述**

**Comment by newpanjing** [comment]
model和admin的代码贴一下。

**Comment by newpanjing** [comment]
升级至simplepro1.0.8，支持Python3.8 与Python3.9
