### ISSUE TITLE
多admin站点编辑页面会报url找不到

### ISSUE THREAD

**Issue by yswtrue** [newpanjing/simpleui#392]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
当配置一个自定义的admin站点，打开changeview会报这个错误
```
Traceback (most recent call last):
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/simpleui/templatetags/simpletags.py", line 474, in get_model_url
    url = reverse(key)
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/yswtrue/Code/lion_backend/.venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'monitor_patrol_changelist' not found. 'monitor_patrol_changelist' is not a valid view function or pattern name.

```

**重现步骤**
** repeat step **
1. 新建一个自定义admin
```

class ManagerAuthenticationForm(AdminAuthenticationForm):
    def confirm_login_allowed(self, user):
        if user.is_active and user.is_staff:
            return None
        return super().confirm_login_allowed(user)


class ManagerAdminSite(AdminSite):
    site_header = _("Manager Admin")
    site_title = _("Welcome")
    index_title = _("Welcome to Manager Admin")
    login_form = ManagerAuthenticationForm

    def has_permission(self, request):
        return request.user.is_active and request.user.is_staff


manager_admin_site = ManagerAdminSite(name="manager_admin")


urlpatterns += i18n_patterns(
    path("manager/", manager_admin_site.urls, name="manager_admin"),
)

```
2.注册model
3.打开新建或者编辑页面

**环境**
** environment**

1.Operating System：Linux
(Windows/Linux/MacOS)....

2.Python Version：3.9.6

3.Django Version：3.0.11

4.SimpleUI Version：2021.8.1

**Description**

**Comment by newpepsi** [comment]
我看了你的代码实现。不太确定使用current app是否合适。
namespace = context.request.resolver_match.namespace
我使用了 context.request.resolver_match.namespace 这个值作为 namespace的值
